# Generated by Django 4.2.7 on 2023-12-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_management', '0002_alter_contacts_email_alter_contacts_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='notes',
            field=models.TextField(),
        ),
    ]
